### ISSUE TITLE
How to cross-compile blocks-runtime?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [mheily/blocks-runtime#1]
Hi Mark,
Sorry for what is probably a trivial question.  
I'm preparing to build libdispatch for a GEODE based platform.  Since libdispatch depends on blocks-runtime, I obviously need to cross compile it. How do I do this?
(I have already built libpthread_workqueue and libkqueue.)

**Comment by mheily** [comment]
Sorry, I have never tried cross-compiling it and have no advice. Have you tried the standard techniques for cross-compiling? 

https://wiki.wxwidgets.org/Cross-Compiling_Under_Linux

**Comment by Napoleon-BlownApart** [comment]
The problem I have is that I don't know how to compile blocks-runtime, at all.  There is no Makefile, autoconf is giving errors, I don't have makeconf, which configure.rb (Ruby) seems to require.

**Comment by mheily** [comment]
Try:

 autoreconf -fvi

Then ./configure

and it will create a Makefile.
